service: nodejs-streams

frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    S3_BUCKET: ${self:service}-${sls:stage}
  s3:
    outputBucket:
      name: ${self:provider.environment.S3_BUCKET}

functions:
  nodejs-streams:
    handler: src/main.handler

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: PK0
            AttributeType: S
          - AttributeName: SK0
            AttributeType: S
        KeySchema:
          - AttributeName: PK0
            KeyType: HASH
          - AttributeName: SK0
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
